version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/barbergo-frontend"  # Cambiado de "/frontend"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "frontend"

  - package-ecosystem: "composer"
    directory: "/api-bar-ber-go"     # Cambiado de "/backend"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "backend"