name: Deploy Backend (api-bar-ber-go) to Azure App Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'api-bar-ber-go/**'  # Solo activa cambios en esta carpeta

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP dependencies
        run: |
          cd api-bar-ber-go
          composer install --no-interaction --no-dev --prefer-dist

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: backend  # Reemplaza con tu nombre en Azure
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: api-bar-ber-go/