name: Deploy Frontend (barbergo-frontend) to Azure Static Web Apps

on:
  push:
    branches: [ "main" ]
    paths:
      - 'barbergo-frontend/**'  # Solo activa cambios en esta carpeta

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and build frontend
        run: |
          cd barbergo-frontend
          npm install
          npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "barbergo-frontend"  # Ruta exacta de tu frontend
          output_location: "dist"            # Carpeta de build (ajusta si es diferente)